<?php

namespace App\Models;

use App\Enums\WorklifePostType;
use App\Enums\AudienceType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class WorklifePost extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'author_employee_id',
        'source_type',
        'source_id',
        'post_type',
        'content',
        'audience_type',
        'audience_id',
        'is_pinned',
        'published_at',
    ];

    protected $casts = [
        'post_type' => WorklifePostType::class,
        'audience_type' => AudienceType::class,
        'is_pinned' => 'boolean',
        'published_at' => 'datetime',
    ];

    public function author(): BelongsTo
    {
        return $this->belongsTo(Employee::class, 'author_employee_id');
    }

    public function source(): MorphTo
    {
        return $this->morphTo();
    }

    public function comments(): HasMany
    {
        return $this->hasMany(WorklifeComment::class)->orderBy('created_at');
    }

    public function likes(): HasMany
    {
        return $this->hasMany(WorklifeLike::class);
    }

    public function reactions(): HasMany
    {
        return $this->hasMany(WorklifeReaction::class);
    }

    public function attachments(): HasMany
    {
        return $this->hasMany(WorklifeAttachment::class);
    }

    public function isLikedBy(Employee $employee): bool
    {
        return $this->likes()->where('employee_id', $employee->id)->exists();
    }

    public function isReactedBy(Employee $employee, string $reactionType = null): bool
    {
        $query = $this->reactions()->where('employee_id', $employee->id);
        if ($reactionType) {
            $query->where('reaction_type', $reactionType);
        }
        return $query->exists();
    }

    public function toggleLike(Employee $employee)
    {
        if ($this->isLikedBy($employee)) {
            $this->likes()->where('employee_id', $employee->id)->delete();
            return false;
        } else {
            $this->likes()->create(['employee_id' => $employee->id]);
            return true;
        }
    }

    public function scopePublished($query)
    {
        return $query->whereNotNull('published_at')
                    ->where('published_at', '<=', now());
    }

    public function scopePinned($query)
    {
        return $query->where('is_pinned', true);
    }

    public function scopeForAudience($query, Employee $employee)
    {
        return $query->where(function ($q) use ($employee) {
            $q->where('audience_type', AudienceType::Company)
              ->orWhere(function ($sq) use ($employee) {
                  $sq->where('audience_type', AudienceType::Department)
                     ->where('audience_id', $employee->department_id);
              })
              ->orWhere(function ($sq) use ($employee) {
                  $sq->where('audience_type', AudienceType::Team)
                     ->where('audience_id', $employee->department_id);
              })
              ->orWhere(function ($sq) use ($employee) {
                  $sq->where('audience_type', AudienceType::Role)
                     ->where('audience_id', $employee->user->roles->first()?->id);
              });
        });
    }

    public function scopeAnnouncements($query)
    {
        return $query->where('post_type', WorklifePostType::Announcement);
    }

    public function scopeAchievements($query)
    {
        return $query->where('post_type', WorklifePostType::Achievement);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('post_type', WorklifePostType::Auto);
    }
}
